sudo: required
services:
    - docker

before_install:
    - docker build -t jaredbrown0/docker-app -f Dockerfile.dev .

script:
    - docker run -e CI=true jaredbrown0/docker-app npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-app"
    env: "DockerApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-984015403767"
    bucket_path: "docker-app"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY